spring.application.name=ScotlandYard
server.port=8999

game.grace-period-seconds=60
game.turn-timer-seconds=120
game.detective-escooter-tickets=10
game.detective-bus-tickets=8
game.detective-train-tickets=4
game.detective-ferry-tickets=2
